export const COMPANY_TRACKS = [
  {
    id: 'google',
    name: 'Google',
    type: 'product',
    initial: 'G',
    color: 'from-blue-600/20 to-green-600/10 text-green-400 border-green-500/20 hover:border-green-500/40',
    badge: 'bg-green-500/10 text-green-400 border-green-500/20',
    difficulty: 'Hard / Competitive',
    problems: '50+ Recommended',
    topics: ['arrays-hashing', 'trees', 'graphs', 'advanced-graphs', '1d-dp', '2d-dp', '1d-dynamic-programming', '2d-dynamic-programming'],
    desc: 'Focus heavily on graphs, complex recursion, topological sort, and advanced DP optimization.',
  },
  {
    id: 'amazon',
    name: 'Amazon',
    type: 'product',
    initial: 'A',
    color: 'from-orange-600/20 to-amber-600/10 text-orange-400 border-orange-500/20 hover:border-orange-500/40',
    badge: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
    difficulty: 'Medium / Hard',
    problems: '45+ Recommended',
    topics: ['arrays-hashing', 'two-pointers', 'sliding-window', 'trees', 'heap-priority-queue', 'greedy'],
    desc: 'Hiring assessments ask heap questions, greedy scheduling, sorting, and tree traversals.',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    type: 'product',
    initial: 'M',
    color: 'from-blue-600/25 to-indigo-600/10 text-blue-400 border-blue-500/20 hover:border-blue-500/40',
    badge: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    difficulty: 'Medium / Hard',
    problems: '40+ Recommended',
    topics: ['arrays-hashing', 'linked-list', 'stack', 'binary-search', 'trees', 'backtracking'],
    desc: 'Microsoft assesses linked list manipulation, system design foundations, recursion, and search trees.',
  },
  {
    id: 'tcs',
    name: 'TCS (NQT / Digital)',
    type: 'service',
    initial: 'T',
    color: 'from-teal-600/20 to-cyan-600/10 text-teal-400 border-teal-500/20 hover:border-teal-500/40',
    badge: 'bg-teal-500/10 text-teal-400 border-teal-500/20',
    difficulty: 'Easy / Medium',
    problems: '20+ Recommended',
    topics: ['arrays-hashing', 'two-pointers', 'math-geometry', 'bit-manipulation'],
    desc: 'Standard aptitude, basic math algorithms, basic string parsing, and arrays hashing.',
  },
  {
    id: 'infosys',
    name: 'Infosys (SP / DSE)',
    type: 'service',
    initial: 'I',
    color: 'from-cyan-600/20 to-sky-600/10 text-cyan-400 border-cyan-500/20 hover:border-cyan-500/40',
    badge: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    difficulty: 'Easy / Medium',
    problems: '25+ Recommended',
    topics: ['arrays-hashing', 'binary-search', 'greedy', '1d-dp', '1d-dynamic-programming'],
    desc: 'Infosys assessments for Specialist Programmer test greedy algorithms, standard binary search, and basic DP.',
  },
  {
    id: 'accenture',
    name: 'Accenture',
    type: 'service',
    initial: 'AC',
    color: 'from-purple-600/20 to-violet-600/10 text-purple-400 border-purple-500/20 hover:border-purple-500/40',
    badge: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    difficulty: 'Easy / Medium',
    problems: '20+ Recommended',
    topics: ['arrays-hashing', 'two-pointers', 'linked-list', 'math-geometry'],
    desc: 'Basic coding assessments, arrays processing, sorting, and linked list traversal.',
  },
];
